export {default as Artists } from "./artists/Artists"
export {default as Albums} from "./albums/Albums"
export {default as Top10s} from "./top_10/Top10s"
export {default as Trendings} from "./trending/Trendings"
export {default as Playlist} from "./playlist/Playlist"
export {default as Favorites} from "./favorites/Favorites"
export {default as Recommended} from "./recommended/Recommended"
export {default as Home} from "./home/Home"